import React, { useState, useEffect } from 'react';
import {
  View, Text, TextInput, TouchableOpacity, StyleSheet,
  ActivityIndicator, Alert, KeyboardAvoidingView, Platform,
} from 'react-native';
import {
  useAuthRequest,
  ResponseType,
  makeRedirectUri,
} from 'expo-auth-session';
import * as WebBrowser from 'expo-web-browser';
import { api } from '../lib/api';
import { useAuthStore } from '../store/auth.store';
import { theme } from '../constants/theme';
import { Feather } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';

WebBrowser.maybeCompleteAuthSession();

// Google OAuth — Web Client ID (same one used by the web app and backend)
const GOOGLE_CLIENT_ID = '930332042684-v66lli0c4anpsn8a4d158vqgbmemrklp.apps.googleusercontent.com';

// Google's OAuth endpoints
const DISCOVERY = {
  authorizationEndpoint: 'https://accounts.google.com/o/oauth2/v2/auth',
  tokenEndpoint: 'https://oauth2.googleapis.com/token',
  revocationEndpoint: 'https://oauth2.googleapis.com/revoke',
};

export default function LoginScreen() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [googleLoading, setGoogleLoading] = useState(false);
  const setAuth = useAuthStore((state) => state.setAuth);
  const navigation = useNavigation<any>();

  // expo-auth-session handles getting the Google access token client-side.
  // This uses the implicit grant flow (ResponseType.Token) which returns
  // an access_token directly without needing a code exchange.
  // The redirect URI is auto-generated by Expo for the current environment.
  const [request, response, promptAsync] = useAuthRequest(
    {
      clientId: GOOGLE_CLIENT_ID,
      responseType: ResponseType.Token,
      scopes: ['openid', 'profile', 'email'],
      usePKCE: false,
      redirectUri: makeRedirectUri(),
    },
    DISCOVERY
  );

  // Handle the OAuth response when Google redirects back to the app
  useEffect(() => {
    if (!response) return;

    if (response.type === 'success') {
      const accessToken = response.params?.access_token;
      if (accessToken) {
        sendTokenToBackend(accessToken);
      } else {
        setGoogleLoading(false);
        Alert.alert('Error', 'No access token received from Google.');
      }
    } else if (response.type === 'error') {
      setGoogleLoading(false);
      Alert.alert('Google Login Failed', response.error?.message || 'Authentication failed.');
    } else if (response.type === 'cancel' || response.type === 'dismiss') {
      setGoogleLoading(false);
    }
  }, [response]);

  // Send the Google access token to our backend for validation and JWT issuance
  const sendTokenToBackend = async (accessToken: string) => {
    try {
      console.log('[Google Auth] Sending access token to backend /auth/google/mobile');
      const res = await api.post('/auth/google/mobile', { accessToken });
      const { access_token, user } = res.data;
      console.log('[Google Auth] Successfully authenticated as:', user?.email);
      setAuth(access_token, user);
    } catch (error: any) {
      const msg = error.response?.data?.message || 'Failed to sign in with Google.';
      console.error('[Google Auth] Backend validation failed:', msg);
      Alert.alert('Login Failed', msg);
    } finally {
      setGoogleLoading(false);
    }
  };

  const handleLogin = async () => {
    if (!email || !password) {
      Alert.alert('Error', 'Please fill in all fields');
      return;
    }
    setLoading(true);
    try {
      const res = await api.post('/auth/login', { email, password });
      setAuth(res.data.access_token, res.data.user);
    } catch (error: any) {
      Alert.alert('Login Failed', error.response?.data?.message || 'Invalid credentials');
    } finally {
      setLoading(false);
    }
  };

  const handleGooglePress = async () => {
    setGoogleLoading(true);
    try {
      await promptAsync();
    } catch (error: any) {
      console.error('[Google Auth] promptAsync error:', error);
      setGoogleLoading(false);
      Alert.alert('Error', 'Could not open Google Sign-In. Please try again.');
    }
  };

  return (
    <KeyboardAvoidingView
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
      style={styles.container}
    >
      <View style={styles.iconContainer}>
        <Feather name="shield" size={48} color={theme.colors.primary} />
      </View>
      <Text style={styles.title}>AI Finance Copilot</Text>
      <Text style={styles.subtitle}>Welcome back to your financial hub</Text>

      <View style={styles.form}>
        <Text style={styles.label}>Email Address</Text>
        <TextInput
          style={styles.input}
          placeholder="Enter your email"
          placeholderTextColor={theme.colors.textMuted}
          value={email}
          onChangeText={setEmail}
          autoCapitalize="none"
          keyboardType="email-address"
        />

        <Text style={styles.label}>Password</Text>
        <TextInput
          style={styles.input}
          placeholder="Enter your password"
          placeholderTextColor={theme.colors.textMuted}
          value={password}
          onChangeText={setPassword}
          secureTextEntry
        />

        <TouchableOpacity style={styles.button} onPress={handleLogin} disabled={loading}>
          {loading ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>Login</Text>}
        </TouchableOpacity>

        <View style={styles.divider}>
          <View style={styles.dividerLine} />
          <Text style={styles.dividerText}>OR</Text>
          <View style={styles.dividerLine} />
        </View>

        <TouchableOpacity
          style={[styles.googleButton, googleLoading && styles.disabledButton]}
          onPress={handleGooglePress}
          disabled={googleLoading}
        >
          {googleLoading ? (
            <ActivityIndicator color={theme.colors.textPrimary} size="small" />
          ) : (
            <>
              <Feather name="globe" size={20} color={theme.colors.textPrimary} />
              <Text style={styles.googleButtonText}>Continue with Google</Text>
            </>
          )}
        </TouchableOpacity>
      </View>

      <View style={styles.footer}>
        <Text style={styles.footerText}>Don't have an account? </Text>
        <TouchableOpacity onPress={() => navigation.navigate('Register')}>
          <Text style={styles.footerLink}>Register here</Text>
        </TouchableOpacity>
      </View>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: theme.spacing.lg,
    backgroundColor: theme.colors.bgBase,
    justifyContent: 'center',
  },
  iconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: theme.colors.primarySoft,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: theme.spacing.lg,
    borderWidth: 1,
    borderColor: 'rgba(124, 58, 237, 0.2)',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: theme.colors.textPrimary,
    textAlign: 'center',
    marginBottom: theme.spacing.xs,
  },
  subtitle: {
    fontSize: 16,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    marginBottom: 48,
  },
  form: { gap: theme.spacing.md },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.colors.textSecondary,
    marginBottom: -8,
  },
  input: {
    borderWidth: 1,
    borderColor: theme.colors.borderDefault,
    borderRadius: theme.radius.md,
    padding: theme.spacing.md,
    fontSize: 16,
    backgroundColor: theme.colors.bgSurface,
    color: theme.colors.textPrimary,
  },
  button: {
    backgroundColor: theme.colors.primary,
    padding: theme.spacing.md,
    borderRadius: theme.radius.md,
    alignItems: 'center',
    marginTop: theme.spacing.sm,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  divider: { flexDirection: 'row', alignItems: 'center', marginVertical: 8 },
  dividerLine: { flex: 1, height: 1, backgroundColor: theme.colors.borderStrong },
  dividerText: { color: theme.colors.textMuted, paddingHorizontal: 16, fontSize: 14, fontWeight: '600' },
  googleButton: {
    flexDirection: 'row',
    backgroundColor: theme.colors.bgSurface,
    padding: theme.spacing.md,
    borderRadius: theme.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.borderStrong,
    gap: 12,
    minHeight: 52,
  },
  disabledButton: { opacity: 0.5 },
  googleButtonText: { color: theme.colors.textPrimary, fontSize: 16, fontWeight: '600' },
  footer: { flexDirection: 'row', justifyContent: 'center', marginTop: 32 },
  footerText: { color: theme.colors.textSecondary, fontSize: 14 },
  footerLink: { color: theme.colors.primary, fontSize: 14, fontWeight: 'bold' },
});
